### ISSUE TITLE
Add lint to Travis CI

### ISSUE THREAD

**Issue by fuhrmannb** [fuhrmannb/node-discovery#6]
To apply lint on Travis CI, specify it in `travis.yml`:
```yaml
install:
  - go get github.com/golang/lint/golint
script:
  - golint github.com/fuhrmannb/node-discovery
```

**Comment by fuhrmannb** [comment]
To apply lint on Travis CI, specify it in `travis.yml`:
```yaml
install:
  - go get github.com/golang/lint/golint
script:
  - golint github.com/fuhrmannb/node-discovery
```
